name: biscuits
version: 2.6.1

description: Service for interacting with the HTTP cookies. A simple and event-based API for to manage cookies.
documentation: https://dev.belin.io/biscuits.dart/api
homepage: https://dev.belin.io/biscuits.dart
issue_tracker: https://github.com/cedx/biscuits.dart/issues
repository: https://github.com/cedx/biscuits.dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  intl: '>=0.15.7 <0.17.0'
  json_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^1.7.2
  build_test: ^0.10.11
  build_web_compilers: ^2.7.1
  grinder: ^0.8.3
  json_serializable: ^3.2.3
  test: ^1.9.4
