name: biscuits
version: 2.6.0

author: CÃ©dric Belin <cedric@belin.io>
description: Service for interacting with the HTTP cookies. A simple and event-based API for handling cookies.
documentation: https://dev.belin.io/biscuits.dart/api
homepage: https://dev.belin.io/biscuits.dart
issue_tracker: https://github.com/cedx/biscuits.dart/issues
repository: https://github.com/cedx/biscuits.dart

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  intl: ^0.16.0
  json_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^1.7.1
  build_test: ^0.10.8
  build_web_compilers: ^2.4.1
  grinder: ^0.8.3
  json_serializable: ^3.2.2
  test: ^1.6.11
